baseURL = "http://chuyii.net"
languageCode = "ja"
title = "chuyii.net"

googleAnalytics = "UA-151539456-1"

[markup.goldmark.renderer]
  unsafe = true

[params]
twitterID = "@_chuyii"
images = ["apple-touch-icon.png"]
